### PR TITLE
Use Win32::GetConsoleCP/GetConsoleOutputCP if available

### LINKED ISSUE #6: Use of "chcp" not permitted under CGI for non-admin users
I started a fairly detailed thread on StackOverflow for this problem: http://stackoverflow.com/questions/19772340/lwpuseragents-env-proxy-gives-access-is-denied-for-non-admin-users

Basically, Encode::Locale is used by LWP::UserAgent which is used by LWP::Simple, which I'm trying to use in a CGI script running under IIS with integrated Windows Authentication.  That means that the CGI runs as the user logged into IIS, most of whom are NOT admins on the webserver.

Encode::Locale's fallback to calling "chcp" (actually, like this: "qx(chcp)") results in an "Access is denied" error.  This is bad enough for Encode::Locale(), but if the CGI includes "use LWP::Simple;" (which is how my script was written), then the error happens at the beginning of the runtime (?), before any of the CGI can be setup, and the webpage user gets an error "The specified CGI application misbehaved by not returning a complete set of HTTP headers".

We need some workaround to NOT use "chcp" in environments like this.

### PR DESCRIPTION
**Pull request by mohawk2**
Fixes #6 and #7.

### CODE REVIEW

**Comment by jandubois** [comment]
I don't understand why you call Win32::GetConsoleCP() for GetACP().  If that is what you want, then it would make sense that the Win32::API fallback calls the same function. And then calling it GetACP() no longer makes sense. :)

**Comment by mohawk2** [comment]
Yes, good catch. Adjusted.

**Comment by gisle** [comment]
Applied.

**Comment by matsp888** [comment]
Yes OK. That seems to fix the problem with using GetConsoleCP() to get the ANSI code page which is totally out of the blue.

**Comment by matsp888** [comment]
The user mohawk2 has with his patch changed the call to GetACP() to GetConsoleCP() to get the system ANSI code page, which is totally wrong. GetConsoleCP() will only get the console input code page, which usually is an OEM code page. I have filed a bug report at rt.cpan.org, not that I know if it will help. Just revert to the old behaviour in 1.03 of calling GetACP() instead, and all will be well.

**Comment by jandubois** [comment]
The part of the patch that tries to use `Win32` makes sense, as `Win32` is a core module. But the code should have used `Win32::GetACP` instead of `Win32::GetConsoleCP`. Then the fallback to `Win32::API` using `GetACP` continues to make sense too (for Perl releases with an old `Win32` version).

**Comment by matsp888** [comment]
It should simply leave the code that calls GetACP() in version 1.03 as it is, and not call GetConsoleCP(), since once again, this function only gets the console input code page, which has nothing to do with the system ANSI code page.

**Comment by matsp888** [comment]
I have been forced to use GetACP() in mh own code because of this change. No fun, but unfortunately necessary....

**Comment by matsp888** [comment]
I've sent a patch to Gisle that reverts to using the old code in 1.03 that uses GetACP() for getting the ANSI code page, since that's the only correct way to do it.

**Pull request closed without merging**
